version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple-eshop
    ports:
      - "5432:5432"
    volumes:
      - simple-eshop-db:/var/lib/postgresql/data
    networks:
      - simple-eshop-network
volumes:
  simple-eshop-db:
    driver: local
networks:
  simple-eshop-network:
    driver: bridge
